- name: Checkout
  uses: actions/checkout@v4
  with:
    fetch-depth: '0'

- name: Install Elocuent (if needed)
  run: |
    npm install -g elocuent

- name: Ensure Meta Directory Exists
  run: |
    mkdir -p meta

- name: Run Elocuent
  run: |
    npx elocuent -d . -o meta/loc.csv
    ls -lah meta/  # Debugging: Show if file was generated

- name: Commit and Push Changes
  run: |
    git config --local user.email "action@github.com"
    git config --local user.name "GitHub Action"
    git pull --rebase  # Ensure latest changes without merge conflicts
    git add -f meta/loc.csv
    git commit -m "Update code statistics" || echo "No changes to commit"
    git push

  permissions:
    contents: write
    pages: write
    id-token: write
